stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

before_script:
  - 'echo "Using Java version:"'
  - 'java -version'
  - 'echo "Using Maven version:"'
  - 'mvn -version'

build:
  stage: build
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/

test:
  stage: test
  script:
    - mvn test
  artifacts:
    paths:
      - target/test-results/
      - target/cucumber-reports/
